-- Run in Supabase SQL Editor
-- This updates the schema to support per-sede configuration

-- 1. Add sede_id column (if table exists) or recreate it
DROP TABLE IF EXISTS public.configuraciones;

CREATE TABLE public.configuraciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave text NOT NULL,
  valor text,
  sede_id bigint NOT NULL,
  CONSTRAINT unique_config_per_sede UNIQUE (clave, sede_id)
);

-- 2. Add Foreign Key for integrity
ALTER TABLE public.configuraciones 
ADD CONSTRAINT fk_config_sede 
FOREIGN KEY (sede_id) REFERENCES public.sedes(id);

-- 3. Enable RLS
ALTER TABLE public.configuraciones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for auth users based on sede" 
ON "public"."configuraciones"
FOR SELECT USING (
  auth.role() = 'authenticated'
  -- Ideally check if user belongs to sede, but for now authenticated is OK for read-only
);

CREATE POLICY "Enable write for auth users based on sede" 
ON "public"."configuraciones"
FOR INSERT WITH CHECK (
  auth.role() = 'authenticated'
);

CREATE POLICY "Enable update for auth users based on sede" 
ON "public"."configuraciones"
FOR UPDATE USING (
  auth.role() = 'authenticated'
);

-- 4. Insert Default Values for known sedes (e.g., Sede 1)
INSERT INTO public.configuraciones (clave, valor, sede_id) VALUES 
 ('inscripciones_abiertas', 'true', 1), 
 ('carga_notas_abierta', 'true', 1),
 ('edicion_horarios_abierta', 'true', 1),
 ('nombre_sede', 'CBUH - Extensión Higuerote', 1),
 ('periodo_actual', '2025-2026', 1)
ON CONFLICT DO NOTHING;
